name: FoundationMinecraft
version: '2.2'
main: pl.lambda.foundationminecraft.FoundationMinecraft
authors: [Lambda]
description: Plugin designed Foundation Minecraft server.
commands:
  chattype:
  depts:
  gamemode:
  keycard:
  money:
  pay:
  setspawn:
  spawn:
  sync:
  setupdeptspawn:
  explosions:
  shop:
  broadcast:
  report:
  tpa:
  tpaccept:
  tpdeny: