name: FoundationMinecraft
version: '2.0'
main: pl.lambda.foundationminecraft.FoundationMinecraft
authors: [Lambda]
description: Plugin designed Foundation Minecraft server.
commands:
  chattype:
  depts:
  gamemode:
  keycard:
  money:
  pay:
  setspawn:
  spawn:
  sync: